### PR TITLE
version 2 -- Refactor service and database configuration

### PR DESCRIPTION
**Pull request by jorhett**
Accept a dict of database configuration values for more flexibility at playbook invocation
Accept dicts of configuration parameters for flexibility at playbook invocation
  - necessary for AWS nodes which need to provide EIP address in config
Handle database init more carefully
Handle database migrate when packages are upgraded
Default TLS enabled to true

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
https://github.com/orgs/ansible-community/teams/hashicorp-tools/discussions/2

**Comment by jorhett** [comment]
> https://github.com/orgs/ansible-community/teams/hashicorp-tools/discussions/2

I can't see that link? You'd have to add me to that team, or quote it here.

**Comment by bbaassssiiee** [comment]
I suggested to add you, I'm not org/team admin.

**Comment by bbaassssiiee** [comment]
I'm not active in the hashitools at the moment.

**Review by bbaassssiiee — APPROVED** [review]

**Pull request merged**
