### PR TITLE
Add AWS and AEAD KMS, API TLS, version 1.0.0

### PR DESCRIPTION
**Pull request by jorhett**
Add Boundary API controller TLS config
Allow API and Transit TLS keys to be supplied via secrets
Add support for AWS and AEAD kms types
Change default config file paths
Change default KMS to `aead`

Breaking changes:
  - Renamed Transit TLS configuration variable names and value format

### CODE REVIEW

**Review by bbaassssiiee — APPROVED** [review]
It's a bit hard to collaborate on a PR with 21 files changed in one commit other than LFTM. 
I would rather have a reason for each commit, or a commit with one change in a file.
But now you are on it, go ahead and make this beautiful in your way. I'm not using this at the moment, and I'm behind in OSS chores, so please merge your own code.

**Comment by jorhett** [comment]
It was actually much bigger, and I tore it down as much as I could. Once I realized I couldn't avoid breaking the `tls_*` params while also providing flexibility going forward all of this ended up coming together as a single change.

I could add the version and initial changelog first if you want, plug reorder the controller/worker separated... but the core of this big change will be the breaking change and I hope it lands with the docs for it and the changelog for it. Hmmm... gimme a sec on that.

**Comment by jorhett** [comment]
Okay, if we merge #21 and #22 and #23 first, this PR becomes much more focused.

**Comment by bbaassssiiee** [comment]
Merged 21, conflicts in 22

**Comment by jorhett** [comment]
> Merged 21, conflicts in 22

Okay, I've pre-rebased them and numbered them in version order. This way the should rebase cleanly. So approve up until you find something objectionable. You can merge the Travis change whenever.

**Comment by bbaassssiiee** [comment]
Please merge you own code, I'm busy doing other things at the moment.

**Pull request merged**
